title: Tweenput Docs
description: Documentation for the Tweenput Godot Addon.
theme: just-the-docs

url: https://Lepakko-dev.github.io/tweenput

aux_links:
  "Tweenput on Github":
  - "//github.com/Lepakko-dev/tweenput"
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# TODO
#logo: "/docs/assets/images/tweenput-logo.png"
#favicon_ico: "/docs/assets/images/favicon.ico"
color_scheme: dark

enable_copy_code_button: true

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html
